# Generated by Django 5.2.4 on 2025-07-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('recieved', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('paymentdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loaner',
                'verbose_name_plural': 'Loaners',
            },
        ),
    ]
