# Generated by Django 5.2.4 on 2025-07-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaner',
            options={},
        ),
        migrations.RemoveField(
            model_name='loaner',
            name='paymentdate',
        ),
        migrations.RemoveField(
            model_name='loaner',
            name='recieved',
        ),
        migrations.RemoveField(
            model_name='loaner',
            name='remaining',
        ),
    ]
