# Generated by Django 5.2.4 on 2025-07-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_loaner_options_remove_loaner_paymentdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaner',
            options={'verbose_name': 'Loaner', 'verbose_name_plural': 'Loaners'},
        ),
        migrations.AddField(
            model_name='loaner',
            name='paymentdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loaner',
            name='recieved',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loaner',
            name='remaining',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
