# Generated by Django 5.2.4 on 2025-07-23 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_loaner_options_loaner_paymentdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.loaner')),
            ],
        ),
    ]
