# Generated by Django 5.2.4 on 2025-07-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaner',
            name='paymentdate',
        ),
        migrations.RemoveField(
            model_name='loaner',
            name='recieved',
        ),
        migrations.RemoveField(
            model_name='loaner',
            name='remaining',
        ),
    ]
