# Generated by Django 5.2.4 on 2025-07-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_loaner_paymentdate_remove_loaner_recieved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='received_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='recieved',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
